services:
  jupyter:
    build:
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      uv run jupyter lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/notebook_dir
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .jupyter:/root/.jupyter
      - ${NotebookDir}:/notebook_dir
