[tool.poetry]
name = "ktaga-lab"
version = "0.1.0"
description = ""
authors = ["ktaga"]
readme = "README.md"
packages = [{include = "ktaga_lab"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
qcodes = "^0.42.1"
ipywidgets = "^8.1.1"
matplotlib = "^3.8.2"
numpy = "^1.23.4"
scipy = "^1.9.3"
sympy = "^1.11.1"
h5py = "^3.7.0"
xarray = "^2023.12.0"
lmfit = "^1.2.2"
pandas = "^1.5.1"
jupyterlab = "^4.0.5"
nbconvert = "^7.2.9"
pandoc = "^2.3"
tqdm = "^4.64.1"
pyvisa = "^1.12.0"
zhinst = "^23.10.3"
plotly = "^5.18.0"
kaleido = "0.2.1"
dash = "^2.14.2"
python-lsp-server = {extras = ["all"], version = "^1.9.0"}
black = "^22.10.0"
isort = "^5.10.1"
hvplot = "^0.9.0"
holoviews = {extras = ["recommended"], version = "^1.18.1"}
pyserial = "^3.5"

nidaqmx = "^0.9.0"
scikit-rf = "^0.30.0"
pythonnet = "^3.0.3"
zhinst-qcodes = "^0.5.2"

[tool.poetry.extras]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
