[tool.poetry]
name = "ktaga-lab-analysis"
version = "0.1.0"
description = "Drivers for the experimental setup and tools for data acquisition and analysis."
authors = ["Kotaro Taga <taga.kotaro.62d@st.kyoto-u.ac.jp>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"

[tool.poetry.extras]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
