[tool.poetry]
name = "ktaga-lab"
version = "0.1.0"
description = ""
authors = ["ktaga"]
readme = "README.md"
packages = [{include = "ktaga_lab"}]

[tool.poetry.dependencies]
python = "^3.10"
qcodes = "^0.35.2"
ipywidgets = "7.7.2"
matplotlib = "^3.6.1"
numpy = "^1.23.4"
scipy = "^1.9.3"
xarray = "^2022.10.0"
lmfit = "^1.0.3"
pandas = "^1.5.1"
jupyterlab = "^3.5.0"
tqdm = "^4.64.1"
pyvisa = "^1.12.0"
zhinst = "^22.8.4"
nidaqmx = "^0.6.4"
plotly = "^5.10.0"
jupyter-dash = "^0.4.2"
jupyterlab-vim = "^0.15.1"
jupyterlab-vimrc = "^0.5.2"
python-lsp-server = {extras = ["all"], version = "^1.5.0"}
jupyterlab-lsp = "^3.10.2"
jupyterlab-code-formatter = "^1.5.3"
black = "^22.10.0"
isort = "^5.10.1"
jupyterlab-git = "^0.39.3"
hvplot = "^0.8.1"
holoviews = {extras = ["recommended"], version = "^1.15.1"}
pyserial = "^3.5"
scikit-rf = "^0.26.0"

[tool.poetry.extras]
jupyterlab-tools = ["jupyterlab-vim","jupyterlab-vimrc"]
zurich = ["zhinst"]
nidaq = ["nidaqmx"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
