[tool.poetry]
name = "ktaga-lab"
version = "0.1.4"
description = "Drivers for the experimental setup and tools for data acquisition and analysis."
authors = ["Kotaro Taga <taga.kotaro.62d@st.kyoto-u.ac.jp>"]
license = "MIT"
readme = "README.md"
packages = [{include = "ktaga_lab"}]
package-mode = true

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
black = "^22.10.0"
dash = "^2.14.2"
h5py = "^3.7.0"
holoviews = {extras = ["recommended"], version = "^1.18.1"}
hvplot = "^0.9.2"
ipywidgets = "^8.1.1"
isort = "^5.13.2"
jupyterlab = "^4.0.12"
kaleido = "0.2.1"
lmfit = "^1.2.2"
matplotlib = "^3.8.2"
nbconvert = "^7.14.2"
nidaqmx = "^0.9.0"
numpy = "^1.26.3"
pandas = "^1.5.3"
pandoc = "^2.3"
plotly = "^5.18.0"
pyserial = "^3.5"
python-lsp-server = {extras = ["all"], version = "^1.10.0"}
pythonnet = "^3.0.3"
pyvisa = "^1.14.1"
qcodes = "^0.43.0"
scikit-rf = "^0.31.0"
scipy = "^1.12.0"
sympy = "^1.12.0"
tqdm = "^4.66.1"
xarray = "^2023.12.0"
zhinst = "^23.10.3"
zhinst-qcodes = "^0.5.3"

jupyterlab-theme-solarized-dark = { version = "^3.0.1", optional = true }
jupyterlab-vim = { version = "^4.1.3", optional = true }

[tool.poetry.extras]
full = ["jupyterlab-theme-solarized-dark","jupyterlab-vim"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
